from app.models import db, Post



def seed_posts():

    post = [Post(userId=1,
                caption='Looking Sexy Boy',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_7.jpg'),
            Post(userId=1,
                caption='Foxxy as ever',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_27.jpg'),
            Post(userId=1,
                caption='Dont waste the anger, channel it',
                photoURL='https://cdn1.dotesports.com/wp-content/uploads/2018/11/19154718/prestigeakali.jpg'),
            Post(userId=1,
                caption='Cant milk those',
                photoURL='https://img.rankedboost.com/wp-content/plugins/league-of-legends-wild-rift/assets/skins/Moo%20Cow%20Alistar.jpg'),
            Post(userId=1,
                caption='im sad',
                photoURL='https://img.rankedboost.com/wp-content/plugins/league-of-legends-wild-rift/assets/skins/Infernal%20Amumu.jpg'),
            Post(userId=1,
                caption='on my wings',
                photoURL='https://static.wikia.nocookie.net/leagueoflegends/images/4/4c/01FR024-full.png/revision/latest?cb=20200407020110'),
            Post(userId=1,
                caption='tibbers',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Annie_8.jpg'),
            Post(userId=1,
                caption='bite my arrow',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_11.jpg'),
            Post(userId=1,
                caption='naturally',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_11.jpg'),
            Post(userId=1,
                caption='spawn',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Azir_0.jpg'),
            Post(userId=1,
                caption='dingaling',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Bard_0.jpg'),
            Post(userId=1,
                caption='ha ha ha ha .. ',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_0.jpg'),
            Post(userId=1,
                caption='inferno',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_4.jpg'),
            Post(userId=1,
                caption='Braum is here',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Braum_0.jpg'),
            Post(userId=1,
                caption='right!',
                photoURL='https://www.pcgamesn.com/wp-content/uploads/2021/03/league-of-legends-battle-academia-caitlyn.jpg'),
            Post(userId=1,
                caption='what a waste, how rude',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Camille_2.jpg'),
            Post(userId=1,
                caption='just a taste',
                photoURL='https://www.mobafire.com/images/champion/skins/landscape/cassiopeia-spirit-blossom.jpg'),
            Post(userId=1,
                caption='the daylight it BURNS',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Chogath_7.jpg'),
            Post(userId=1,
                caption='speed of heat',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Corki_0.jpg'),
            Post(userId=1,
                caption='Noxus will rise',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Darius_15.jpg'),
            Post(userId=1,
                caption='chosen of the moon',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Diana_2.jpg'),
            Post(userId=1,
                caption='mundo will go where he pleases',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/DrMundo_0.jpg'),
            Post(userId=1,
                caption='the league of draven',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Draven_2.jpg'),
            Post(userId=1,
                caption='fool me once and ill just rewind',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ekko_19.jpg'),
            Post(userId=1,
                caption='every web a masterpiece',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Elise_0.jpg'),
            Post(userId=1,
                caption='sealed with the kiss',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Evelynn_6.jpg'),
            Post(userId=1,
                caption='ya ya ya i got it i got it',
                photoURL='https://cdn1.dotesports.com/wp-content/uploads/2020/08/26093146/Ezreal.jpg'),
            Post(userId=1,
                caption='the end is near',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_0.jpg'),
            Post(userId=1,
                caption='precision and grace',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiora_22.jpg'),
            Post(userId=1,
                caption='swimingly, one jump ahead of you',
                photoURL='https://i.pinimg.com/originals/ae/16/0c/ae160cc092f339d1d91062ca6f8c0bf9.jpg'),
            Post(userId=1,
                caption='im a big man with big needs',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Galio_0.jpg'),
            Post(userId=1,
                caption='deadman tell my tail',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gangplank_8.jpg'),
            Post(userId=1,
                caption='DEMACIIAAAA',
                photoURL='https://pbs.twimg.com/profile_images/723255461613604865/F8CLdnlI.jpg'),
            Post(userId=1,
                caption='DA DA',
                photoURL='https://i.ytimg.com/vi/KCHiM5jkHb0/maxresdefault.jpg'),
            Post(userId=1,
                caption='if your buying im in',
                photoURL='https://64.media.tumblr.com/tumblr_m66w6wgr2t1r75hcfo1_1280.jpg'),
            Post(userId=1,
                caption='end of the line',
                photoURL='https://i.imgur.com/LeZF17r.jpg'),
            Post(userId=1,
                caption='behold the might of the shadow isles',
                photoURL='https://static2.lolwallpapers.net/2015/01/Reaper-Hecarim.jpg'),
            Post(userId=1,
                caption='hmmm verrrrrrrrryyyyyyy interesting',
                photoURL='https://i.pinimg.com/originals/e1/9f/ea/e19feafed3561da6234e2dbba79cc042.jpg'),
            Post(userId=1,
                caption='my name is illaoi',
                photoURL='https://i.pinimg.com/236x/5e/1f/b3/5e1fb329e7cb351a9aa5f213de0591db--legends-video-games.jpg'),
            Post(userId=1,
                caption='and now i dance alone',
                photoURL='https://m.media-amazon.com/images/I/61NJ63A90VL._AC_SX679_.jpg'),
            Post(userId=1,
                caption='knowledge is power',
                photoURL='https://i.redd.it/g7hd51gdpfv31.jpg'),
            Post(userId=1,
                caption='the tempest is at your command',
                photoURL='https://esportsedition.com/wp-content/uploads/2016/03/Janna.jpg'),
            Post(userId=1,
                caption='by my willllll',
                photoURL='https://pbs.twimg.com/media/EausR70UwAApcMg.jpg'),
            Post(userId=1,
                caption='imagine if i had a real weapon',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jax_1.jpg'),
            Post(userId=1,
                caption='to the skies',
                photoURL='https://assets-esports.thescore.com/uploads/image/file/13852/cropped_Jayce_2.jpg?ts=1486655335'),
            Post(userId=1,
                caption='hrrrp where there drama in that',
                photoURL='https://i.redd.it/at6ebbz7ous41.png'),
            Post(userId=1,
                caption='jinxed stands for jinxed',
                photoURL='https://i.pinimg.com/originals/eb/2c/14/eb2c14c4effe7277d069c41dd482ab10.jpg'),
            Post(userId=1,
                caption='fly or fight',
                photoURL='https://lolskinshop.com/wp-content/uploads/2019/10/kaisa-invictus-gaming.jpg'),
            Post(userId=1,
                caption='the wounds of betrayal never heal',
                photoURL='https://www.mobafire.com/images/champion/skins/landscape/kalista-marauder.jpg'),
            Post(userId=1,
                caption='we must make all our choices',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karma_19.jpg'),
            Post(userId=1,
                caption='for the unliving',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karthus_1.jpg'),
            Post(userId=1,
                caption='your magic is powerless against me',
                photoURL='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-kLx4LgiNxFTf93A7ktF-un93Blfzvq2HVw&usqp=CAU'),
            Post(userId=1,
                caption='violence solves everything',
                photoURL='https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/16ba7581-d40f-45a6-ad94-b1e783d22fb6/de0lpnj-0c5cfa07-ff66-4790-9e9b-8c580740b972.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvMTZiYTc1ODEtZDQwZi00NWE2LWFkOTQtYjFlNzgzZDIyZmI2XC9kZTBscG5qLTBjNWNmYTA3LWZmNjYtNDc5MC05ZTliLThjNTgwNzQwYjk3Mi5qcGcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.jRcEeQMxGjRbhpWEzJR0UI_eFYQmhUoYpZBm3wBoNMA'),
            Post(userId=1,
                caption='eye for an eye',
                photoURL='https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayle_3.jpg'),
            Post(userId=1,
                caption='its hard to beat a person who never gives up',
                photoURL='https://static.wikia.nocookie.net/leagueoflegends/images/7/7d/Kayn_OriginalCentered.jpg/revision/latest/scale-to-width-down/1280?cb=20180414184150'),
            Post(userId=1,
                caption='the eyes never lie',
                photoURL='https://i.pinimg.com/originals/f8/56/ca/f856ca90f2077ff12a90bd39b0492942.jpg'),
            Post(userId=1,
                caption='channnggee is gooood',
                photoURL='https://media.comicbook.com/2017/11/league-of-legends-kha-zix-1050705-1280x0.jpg')]


    db.session.add(post)

    db.session.commit()



def undo_posts():
    db.session.execute('TRUNCATE posts;')
    db.session.commit()
