from app.models import db, Post, User
import random


def seed_posts():

    users = len(User.query.all())
    captionList = [
        'My team winning the LCS',
        'Looking Sexy Boy',
        'Foxxy as ever',
        'Dont waste the anger, channel it',
        'Cant milk those',
        'im sad',
        'on my wings',
        'tibbers',
        'bite my arrow',
        'naturally',
        'spawn',
        'dingaling',
        'ha ha ha ha .. ',
        'inferno',
        'Braum is here',
        'right!',
        'what a waste, how rude',
        'just a taste',
        'the daylight it BURNS',
        'speed of heat',
        'Noxus will rise',
        'chosen of the moon',
        'mundo will go where he pleases',
        'the league of draven',
        'fool me once and ill just rewind',
        'every web a masterpiece',
        'sealed with the kiss',
        'ya ya ya i got it i got it',
        'the end is near',
        'precision and grace',
        'swimingly, one jump ahead of you',
        'im a big man with big needs',
        'deadman tell my tail',
        'DEMACIIAAAA',
        'DA DA',
        'if your buying im in',
        'end of the line',
        'behold the might of the shadow isles',
        'hmmm verrrrrrrrryyyyyyy interesting',
        'my name is illaoi',
        'and now i dance alone',
        'knowledge is power',
        'the tempest is at your command',
        'by my willllll',
        'imagine if i had a real weapon',
        'to the skies',
        'hrrrp where there drama in that',
        'jinxed stands for jinxed',
        'fly or fight',
        'the wounds of betrayal never heal',
        'we must make all our choices',
        'for the unliving',
        'your magic is powerless against me',
        'violence solves everything',
        'eye for an eye',
        'its hard to beat a person who never gives up',
        'the eyes never lie',
        'channnggee is gooood',
        'Never one.. ...without the other',
        'Oh, I knew you was all yeller!',
        'Time to feast!',
        'Are you Certain?',
        'Your will, my hands',
        'The dawn has arrived.',
        'Me? A dream come true..',
        'Foolish Child',
        'Everybody dies.. Some just need a little help.',
        'Pleased to meet you!',
        'Lets light it up!',
        'Rock Solid',
        'Oblivion Awaits!',
        'The Isles will bloom again!',
        'My blade is yours',
        'Fortune does not favor fools',
        'Destiny. Domination. Deceit.',
        'I am bound, but I will not break',
        'I decide what the tide will bring!',
        'The cycle of life and death continues.. We will live, they will die',
        'Beware the depths',
        'Neeko is the best decision!',
        'They will fear the wild!',
        'Embrace the darkness..',
        'Every adventure is better with a friend!',
        'Leave nothing behind!',
        'We will kill your enemies.. that will be fun.',
        'Fine, we go',
        'In battle, we are reborn',
        'I am no hero, just a Yordle with a hammer!',
        'Sink em all!',
        'You may now appreciate me',
        'Justice takes wing!',
        'Lets Dance!',
        'ok',
        'grrrrrrr...',
        'Nothing gets in, no one gets out',
        'As I live, all will die',
        'Tonight, we hunt!',
        'What is broken can be reforged',
        'Lets get in the fight!',
        'A step ahead of cataclysm',
        'You want style? You found her.',
        'Trust nothing but your strength',
        'No one fights alone in the Mist',
        'Lets change the world!',
        'I am undisputed.',
        'How about a magic trick?',
        'A demonstration of superior judgement',
        'They are nothing before me',
        'How about a drink?'
        'Rest is for the living!',
        'I always take my toll - blood, or gold.',
        'My stinger brings ugly death',
        'What masterpiece shall we play today?',
        'Let me guide you',
        'Fear the power you do not see',
        'No more cages!',
        'So much untapped power',
        'Call me King! Call me Demon! Water forgets the name of the drowned..'
        'Know the loom. Be the stone',
        'Live and die by the blade.',
        'That glimer of hope you see, thats me',
        'CAPTAIN TEEMO ON DUTY!',
        ' What delightful agony we shall inflict.',
        'Once a bandle gunner, always a bandle gunner!',
        'Time to troll!',
        'This will be a slaughter!',
        'Lady Luck is Smiling..',
        'What doesnt kill you just isnt finished yet',
        'Our rage is beyond your controll',
        'You cannot know strength... until you are broken.',
        'This guilty will know agony',
        'Let us hunt those who have fallen to darkness',
        'Know that if the tables were turned, I would show you no mercy!',
        'Knowledge through... disintegration',
        'Love ruins all',
        'Join the glorious evolution',
        'The rivers will run red',
        'Feel the power of the wild',
        'Blood runs... they all run',
        'I will be the best',
        'I can never resist an invitation to dance',
        'I will be free.',
        'To the arena!',
        'Death is like the wind -- always by my side',
        'One to cut, one to seal',
        'Fear not.. I will make use of your corpse.',
        'You and Me, we got this!',
        'I was made for this... literally',
        'The unseen blade is the deadliest',
        'This will be a blast!',
        'I knew you would do that...',
        'Yes! This will be fun! Right?',
        'Feel the thorns embrace!'
    ]
    capt = len(captionList)

    urlList = [
        'https://static.invenglobal.com/upload/image/2017/02/22/i1487753623863997.jpeg', #Demo User
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Anivia_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aphelios_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Annie_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Azir_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Bard_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Braum_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Camille_2.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Cassiopeia_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Chogath_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Corki_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Darius_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Diana_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/DrMundo_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Draven_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ekko_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Elise_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Evelynn_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fizz_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/XinZhao_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Galio_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gangplank_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Garen_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gnar_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gragas_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Graves_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Hecarim_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Heimerdinger_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Illaoi_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Irelia_0.jpg',
        'https://i.redd.it/g7hd51gdpfv31.jpg', #Ivern
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Janna_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jarvan_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jax_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jayce_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jhin_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kaisa_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kalista_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karma_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karthus_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kassadin_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Katarina_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayle_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayn_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kennen_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Khazix_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kindred_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kled_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/KogMaw_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leblanc_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/LeeSin_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leona_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lillia_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lissandra_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lucian_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lulu_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malphite_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malzahar_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Maokai_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MasterYi_10.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MissFortune_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Mordekaiser_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Morgana_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nami_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nasus_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nautilus_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Neeko_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nidalee_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nocturne_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nunu_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Olaf_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Orianna_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ornn_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pantheon_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Poppy_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Qiyana_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Quinn_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rakan_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rammus_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/RekSai_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rell_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Renekton_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rengar_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Riven_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rumble_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ryze_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Samira_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sejuani_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Senna_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Seraphine_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shaco_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shen_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shyvana_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Singed_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sion_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sivir_16.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Skarner_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sona_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Soraka_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Swain_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sylas_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Syndra_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/TahmKench_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taliyah_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Talon_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taric_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Thresh_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Tristana_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Trundle_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Tryndamere_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/TwistedFate_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Twitch_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Udyr_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Urgot_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Varus_0.jpg,',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vayne_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Veigar_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Velkoz_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vi_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Viktor_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vladimir_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Volibear_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Warwick_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MonkeyKing_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xayah_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xerath_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/XinZhao_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yone_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yorick_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yuumi_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zac_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zilean_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zoe_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zyra_0.jpg'

    ]

    images = len(urlList)

    count = 0
    while count < 154:
        new_post = Post(
            userId = (count + 1),
            photoURL = urlList[count],
            caption = captionList[count],
            vaulted = False
        )

        count = count + 1
        db.session.add(new_post)



    db.session.commit()









def undo_posts():
    db.session.execute('TRUNCATE posts;')
    db.session.commit()
