from app.models import db, Post, User
import random


def seed_posts():

    users = len(User.query.all())
    captionList = [
        'My team winning the LCS',
        'Looking Sexy Boy',
        'Foxxy as ever',
        'Dont waste the anger, channel it',
        'Cant milk those',
        'im sad',
        'on my wings',
        'tibbers',
        'bite my arrow',
        'naturally',
        'spawn',
        'dingaling',
        'ha ha ha ha .. ',
        'inferno',
        'Braum is here',
        'right!',
        'what a waste, how rude',
        'just a taste',
        'the daylight it BURNS',
        'speed of heat',
        'Noxus will rise',
        'chosen of the moon',
        'mundo will go where he pleases',
        'the league of draven',
        'fool me once and ill just rewind',
        'every web a masterpiece',
        'sealed with the kiss',
        'ya ya ya i got it i got it',
        'the end is near',
        'precision and grace',
        'swimingly, one jump ahead of you',
        'im a big man with big needs',
        'deadman tell my tail',
        'DEMACIIAAAA',
        'DA DA',
        'if your buying im in',
        'end of the line',
        'behold the might of the shadow isles',
        'hmmm verrrrrrrrryyyyyyy interesting',
        'my name is illaoi',
        'and now i dance alone',
        'knowledge is power',
        'the tempest is at your command',
        'by my willllll',
        'imagine if i had a real weapon',
        'to the skies',
        'hrrrp where there drama in that',
        'jinxed stands for jinxed',
        'fly or fight',
        'the wounds of betrayal never heal',
        'we must make all our choices',
        'for the unliving',
        'your magic is powerless against me',
        'violence solves everything',
        'eye for an eye',
        'its hard to beat a person who never gives up',
        'the eyes never lie',
        'channnggee is gooood',
    ]
    capt = len(captionList)

    urlList = [
        'https://static.invenglobal.com/upload/image/2017/02/22/i1487753623863997.jpeg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_7.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_27.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_15.jpg',
        'https://img.rankedboost.com/wp-content/plugins/league-of-legends-wild-rift/assets/skins/Moo%20Cow%20Alistar.jpg',
        'https://img.rankedboost.com/wp-content/plugins/league-of-legends-wild-rift/assets/skins/Infernal%20Amumu.jpg',
        'https://c4.wallpaperflare.com/wallpaper/295/161/138/league-of-legends-anivia-wallpaper-preview.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aphelios_1.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Annie_8.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_11.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_11.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Azir_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Bard_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_4.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Braum_0.jpg',
        'https://www.pcgamesn.com/wp-content/uploads/2021/03/league-of-legends-battle-academia-caitlyn.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Camille_2.jpg',
        'https://www.mobafire.com/images/champion/skins/landscape/cassiopeia-spirit-blossom.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Chogath_7.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Corki_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Darius_15.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Diana_2.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/DrMundo_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Draven_2.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ekko_19.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Elise_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Evelynn_6.jpg',
        'https://cdn1.dotesports.com/wp-content/uploads/2020/08/26093146/Ezreal.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiora_22.jpg',
        'https://i.pinimg.com/originals/ae/16/0c/ae160cc092f339d1d91062ca6f8c0bf9.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Galio_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gangplank_8.jpg',
        'https://pbs.twimg.com/profile_images/723255461613604865/F8CLdnlI.jpg',
        'https://i.ytimg.com/vi/KCHiM5jkHb0/maxresdefault.jpg',
        'https://www.mobafire.com/images/champion/skins/landscape/gragas-warden.jpg',
        'https://i.imgur.com/LeZF17r.jpg',
        'https://static2.lolwallpapers.net/2015/01/Reaper-Hecarim.jpg',
        'https://i.pinimg.com/originals/e1/9f/ea/e19feafed3561da6234e2dbba79cc042.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Illaoi_10.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Irelia_17.jpg',
        'https://i.redd.it/g7hd51gdpfv31.jpg',
        'https://esportsedition.com/wp-content/uploads/2016/03/Janna.jpg',
        'https://pbs.twimg.com/media/EausR70UwAApcMg.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jax_1.jpg',
        'https://assets-esports.thescore.com/uploads/image/file/13852/cropped_Jayce_2.jpg?ts=1486655335',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jhin_2.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_13.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kaisa_26.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kalista_2.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karma_19.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karthus_1.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kassadin_5.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Katarina_8.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayle_3.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayn_2.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kennen_6.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Khazix_4.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kindred_0.jpg',
        'https://blogoflegends.com/files/2019/03/Kled_2.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/KogMaw_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leblanc_20.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/LeeSin_11.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leona_10.jpg',
        'https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt05a0dbd4c9c7f6c6/5efbce71b52fb75925ee3344/01_Lillia-Splash-Base.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lissandra_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lucian_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lulu_0.jpg',
        'https://blogoflegends.com/files/2020/10/Lux_7.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malphite_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malzahar_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Maokai_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MasterYi_10.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MissFortune_8.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Mordekaiser_0.jpg',
        'https://cdn1.dotesports.com/wp-content/uploads/2020/08/03152729/coven-morgana.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nami_15.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nasus_0.jpg',
        'https://i.ytimg.com/vi/TkJUpzZo6yE/maxresdefault.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Neeko_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nidalee_0.jpg',
        'https://blogoflegends.com/files/2019/05/Nocturne_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nunu_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Olaf_0.jpg',
        'https://www.mobafire.com/images/champion/skins/landscape/orianna-dark-star.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ornn_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pantheon_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Poppy_0.jpg',
        'https://cdn1.dotesports.com/wp-content/uploads/2021/03/02074436/Pyke_0-1.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Qiyana_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Quinn_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rakan_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rammus_1.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/RekSai_0.jpg',
        'https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt6767a7ffeb343452/5fb6c9834e40cf53001f8712/Base_Rell_Final.jpg',
        'https://blogoflegends.com/files/2017/08/Renekton_4.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rengar_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Riven_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rumble_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ryze_2.jpg',
        'https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt1215d602efe4f66a/5f48197070ca0f65ba109ee6/Samira_BaseSplash_FINAL_optimized.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sejuani_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Senna_0.jpg',
        'https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt6921c7fcf379895c/5f7e3beaf11ee70e9e14e7a2/ser450kb.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shaco_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shen_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shyvana_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Singed_0.jpg',
        'https://cdn1.dotesports.com/wp-content/uploads/2018/10/30095013/Sion_WarmongerSkin.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sivir_16.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Skarner_0.jpg',
        'https://cdn1.dotesports.com/wp-content/uploads/2019/06/26200806/Sona-Odyssey.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Soraka_15.jpg',
        'https://lolstatic-a.akamaihd.net/frontpage/apps/prod/rg-swain-reveal/en_US/f4b05129ff4965f7cae70871504158000cbe0fc7/assets/downloads/wallpapers/swain-1920x1200.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sylas_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Syndra_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/TahmKench_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taliyah_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Talon_0.jpg',
        'https://media.comicbook.com/2017/11/league-of-legends-taric-1056843-1280x0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Thresh_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Tristana_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Trundle_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Tryndamere_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/TwistedFate_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Twitch_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Udyr_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Urgot_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Varus_0.jpg,',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vayne_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Veigar_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Velkoz_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vi_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Viktor_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vladimir_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Volibear_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Warwick_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MonkeyKing_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xayah_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xerath_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/XinZhao_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yone_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yorick_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yuumi_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zac_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zilean_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zoe_0.jpg',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zyra_0.jpg'

    ]

    images = len(urlList)

    count = 0
    while count < 155:
        new_post = Post(
            userId = (count + 1),
            photoURL = urlList[count],
            caption = captionList[count],
            vaulted = False
        )

        count = count + 1
        db.session.add(new_post)

    db.session.commit()









def undo_posts():
    db.session.execute('TRUNCATE posts;')
    db.session.commit()
