from werkzeug.security import generate_password_hash
from app.models import db, User


# Adds a demo user, you can add other users here if you want


def seed_users():
    password = 'password'

    demo = User(userName='Demo',
                firstName='Demo',
                lastName='User',
                email='demo@aa.io',
                profileImage="https://mir-s3-cdn-cf.behance.net/projects/404/3730bc103666837.Y3JvcCwzMzc1LDI2MzksMCwxMDg.jpg",
                password=password)

    db.session.add(demo)
    nameList = [
        "Aatrox",
        "Ahri",
        "Akali",
        "Alistar",
        "Amumu",
        "Anivia",
        "Annie",
        "Aphelios",
        "Ashe",
        "Aurelion-Sol",
        "Azir",
        "Bard",
        "Blitzcrank",
        "Brand",
        "Braum",
        "Caitlyn",
        "Camille",
        "Cassiopeia",
        "Cho'Gath",
        "Corki",
        "Darius",
        "Diana",
        "Dr.Mundo",
        "Draven",
        "Ekko",
        "Elise",
        "Evelynn",
        "Ezreal",
        "Fiddlesticks",
        "Fiora",
        "Fizz",
        "Galio",
        "Gangplank",
        "Garen",
        "Gnar",
        "Gragas",
        "Graves",
        "Hecarim",
        "Heimerdinger",
        "Illaoi",
        "Irelia",
        "Ivern",
        "Janna",
        "JarvanIV",
        "Jax",
        "Jayce",
        "Jhin",
        "Jinx",
        "Kai'Sa",
        "Kalista",
        "Karma",
        "Karthus",
        "Kassadin",
        "Katarina",
        "Kayle",
        "Kayn",
        "Kennen",
        "Kha'Zix",
        "Kindred",
        "Kled",
        "Kog'Maw",
        "LeBlanc",
        "Lee-Sin",
        "Leona",
        "Lillia",
        "Lissandra",
        "Lucian",
        "Lulu",
        "Lux",
        "Malphite",
        "Malzahar",
        "Maokai",
        "Master Yi",
        "Miss Fortune",
        "Mordekaiser",
        "Morgana",
        "Nami",
        "Nasus",
        "Nautilus",
        "Neeko",
        "Nidalee",
        "Nocturne",
        "Nunu",
        "Olaf",
        "Orianna",
        "Ornn",
        "Pantheon",
        "Poppy",
        "Pyke",
        "Qiyana",
        "Quinn",
        "Rakan",
        "Rammus",
        "Rek'Sai",
        "Rell",
        "Renekton",
        "Rengar",
        "Riven",
        "Rumble",
        "Ryze",
        "Samira",
        "Sejuani",
        "Senna",
        "Seraphine",
        "Sett",
        "Shaco",
        "Shen",
        "Shyvana",
        "Singed",
        "Sion",
        "Sivir",
        "Skarner",
        "Sona",
        "Soraka",
        "Swain",
        "Sylas",
        "Syndra",
        "Tahm-Kench",
        "Taliyah",
        "Talon",
        "Taric",
        "Teemo",
        "Thresh",
        "Tristana",
        "Trundle",
        "Tryndamere",
        "Twisted Fate",
        "Twitch",
        "Udyr",
        "Urgot",
        "Varus",
        "Vayne",
        "Veigar",
        "Vel'Koz",
        "Vi",
        "Viktor",
        "Vladimir",
        "Volibear",
        "Warwick",
        "Wukong",
        "Xayah",
        "Xerath",
        "Xin-Zhao",
        "Yasuo",
        "Yone",
        "Yorick",
        "Yuumi",
        "Zac",
        "Zed",
        "Ziggs",
        "Zilean",
        "Zoe",
        "Zyra"

    ]
    profilePicList = [
        "https://www.arablol.com/images/champion/Aatrox.png",
        "https://i.redd.it/eo10a5muwws51.png",
        "https://www.mobafire.com/images/avatars/akali-classic.png",
        "https://www.mobafire.com/images/avatars/alistar-classic.png",
        "https://www.mobafire.com/images/avatars/amumu-classic.png",
        "https://bubiroyun.com/wp-content/uploads/2020/01/anivia.png",
        "https://i.redd.it/vs4nqxqekxw31.png",
        "https://www.mobafire.com/images/avatars/aphelios-classic.png",
        "https://www.arablol.com/images/champion/Ashe.png",
        "https://www.mobafire.com/images/avatars/aurelion-sol-classic.png",
        "https://i.redd.it/74qmf31ku8161.png",
        "https://i.redd.it/2vbdbmsovwz31.jpg",
        "https://www.mobafire.com/images/avatars/blitzcrank-classic.png",
        "https://www.mobafire.com/images/avatars/brand-classic.png",
        "https://www.gamersdecide.com/sites/default/files/img_7320.png",
        "https://b.thumbs.redditmedia.com/gwyQkEmvIvonVA-hYPUi5hsHvIQJuKLmd1ZtGeFPtqM.png",
        "https://www.mobafire.com/images/avatars/camille-classic.png",
        "https://www.mobafire.com/images/avatars/cassiopeia-classic.png",
        "https://www.mobafire.com/images/avatars/chogath-classic.png",
        "https://www.mobafire.com/images/avatars/corki-classic.png",
        "https://c2812.cloudnet.cloud/images/avatars/darius-classic.png",
        "https://i.redd.it/ulitet3cfan41.png",
        "https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt8bccc401a842ce7a/5ed7f58a4e88032c940ca233/Author_Icon_Mundo_Team.png",
        "https://1.bp.blogspot.com/-3ejoBqAzfE4/W1skXB8sGCI/AAAAAAAAMC4/4bTZpUGsUKkLb_F8eMDx82Nj4EhRAXNKQCLcBGAs/s1600/draven-champion-quotes.png",
        "https://www.mobafire.com/images/avatars/ekko-classic.png",
        "https://www.mobafire.com/images/avatars/elise-classic.png",
        "https://www.mobafire.com/images/avatars/evelynn-classic.png",
        "https://www.mobafire.com/images/avatars/ezreal-classic.png",
        "https://www.mobafire.com/images/avatars/fiddlesticks-classic.png",
        "https://www.mobafire.com/images/avatars/fiora-classic.png",
        "https://www.mobafire.com/images/avatars/fizz-classic.png",
        "https://www.mobafire.com/images/avatars/galio-classic.png",
        "https://pm1.narvii.com/5810/606022164b501380e79e6cbb5d6507dfb36e5abc_hq.jpg",
        "https://c2812.cloudnet.cloud/images/avatars/garen-classic.png",
        "https://www.mobafire.com/images/avatars/gnar-classic.png",
        "https://www.mobafire.com/images/avatars/gragas-classic.png",
        "https://www.mobafire.com/images/champion/square/graves.png",
        "https://arablol.com/images/champion/Hecarim.png",
        "https://1.bp.blogspot.com/-Fgc4eWYoNiY/XpYjaR5C2SI/AAAAAAABilc/mwUQKD7jzJUA0XKdjx2OH8pV0s3ZwKzUgCLcBGAsYHQ/s200/4557.jpg",
        "https://www.mobafire.com/images/avatars/illaoi-classic.png",
        "https://4.bp.blogspot.com/-tdxpnSzbcZA/W3Mx4y8kiZI/AAAAAAABFV0/hF4o7DwC-L8oDKz7lGdA-wT5J8dYEu5ygCLcBGAs/s200/3599.jpg",
        "https://www.mobafire.com/images/avatars/ivern-classic.png",
        "https://c2812.cloudnet.cloud/images/avatars/janna-classic.png",
        "https://www.mobafire.com/images/avatars/jarvan-iv-classic.png",
        "https://www.mobafire.com/images/avatars/jax-classic.png",
        "https://www.mobafire.com/images/avatars/jayce-classic.png",
        "https://seek-team-prod.s3.fr-par.scw.cloud/users/5f5f1b45cde97531818949.jpg",
        "https://www.mobafire.com/images/avatars/jinx-classic.png",
        "https://tdj.gg/uploads/attachs/57212_kaisa.png",
        "https://www.mobafire.com/images/avatars/kalista-classic.png",
        "https://www.mobafire.com/images/avatars/karma-classic.png",
        "https://www.mobafire.com/images/champion/square/karthus.png",
        "https://championstats.net/files/tiles/Kassadin_0.jpg",
        "https://64.media.tumblr.com/83e036d9e30fb855711a7705839e3e03/6928dbeea3857508-fc/s400x600/4902fa2c98e57f745a0bf2d31a17e9a56a347629.png",
        "https://64.media.tumblr.com/96438af27f809f5f280fc61cac3b8ebe/tumblr_pn8jtcOcVl1y5iq9mo1_250.png",
        "https://d181w3hxxigzvh.cloudfront.net/wp-content/uploads/2017/09/Kayn_Splash_Tile_0.jpg",
        "https://ddragon.leagueoflegends.com/cdn/11.6.1/img/profileicon/1107.png",
        "https://www.mobafire.com/images/avatars/khazix-classic.png",
        "https://1.bp.blogspot.com/-3BT_ySVe1Fk/Xwi-hFA1UEI/AAAAAAABoYU/y2vAk1wZ0aonxzN_csAM84PCkL4ZPVyNwCLcBGAsYHQ/s1600/4659.jpg",
        "https://www.mobafire.com/images/avatars/kled-classic.png",
        "https://1.bp.blogspot.com/-dWKvczMXjZU/XvJz_tDIv7I/AAAAAAABnAo/qXie5otd95w0niR_TvWpNU4ebzzTuT9vgCLcBGAsYHQ/s320/KogMawLoadScreen_19.PIE_C_10_14.jpg",
        "https://www.mobafire.com/images/avatars/leblanc-classic.png",
        "https://www.mobafire.com/images/avatars/lee-sin-classic.png",
        "https://www.mobafire.com/images/avatars/leona-classic.png",
        "https://www.mobafire.com/images/avatars/lillia-classic.png",
        "https://www.mobafire.com/images/avatars/lissandra-classic.png",
        "https://www.mobafire.com/images/avatars/lucian-classic.png",
        "https://www.mobafire.com/images/avatars/lulu-classic.png",
        "https://1.bp.blogspot.com/-B480GAAaSMA/WygGRb6Gi1I/AAAAAAABBpo/ZLC5opyFjbwhtIkwhfsLh5el3xBNtmkRgCEwYBhgL/s1600/3543.jpg",
        "https://www.mobafire.com/images/avatars/malphite-classic.png",
        "https://www.mobafire.com/images/avatars/malzahar-classic.png",
        "https://www.mobafire.com/images/avatars/maokai-classic.png",
        "https://www.mobafire.com/images/avatars/master-yi-classic.png",
        "https://www.mobafire.com/images/avatars/miss-fortune-classic.png",
        "https://www.mobafire.com/images/avatars/mordekaiser-classic.png",
        "https://www.mobafire.com/images/avatars/morgana-classic.png",
        "https://www.mobafire.com/images/avatars/nami-classic.png",
        "https://www.mobafire.com/images/avatars/nasus-classic.png",
        "https://www.mobafire.com/images/avatars/nautilus-classic.png",
        "https://www.mobafire.com/images/avatars/neeko-classic.png",
        "https://www.mobafire.com/images/avatars/nidalee-classic.png",
        "https://www.mobafire.com/images/avatars/nocturne-classic.png",
        "https://www.mobafire.com/images/champion/square/nunu-willump.png",
        "https://www.mobafire.com/images/avatars/olaf-classic.png",
        "https://www.mobafire.com/images/avatars/orianna-classic.png",
        "https://www.mobafire.com/images/avatars/ornn-classic.png",
        "https://www.mobafire.com/images/avatars/pantheon-classic.png",
        "https://www.mobafire.com/images/avatars/poppy-classic.png",
        "https://www.mobafire.com/images/avatars/pyke-classic.png",
        "https://www.mobafire.com/images/avatars/qiyana-classic.png",
        "https://www.mobafire.com/images/avatars/quinn-classic.png",
        "https://www.mobafire.com/images/avatars/rakan-classic.png",
        "https://www.mobafire.com/images/avatars/rammus-classic.png",
        "https://www.mobafire.com/images/avatars/reksai-classic.png",
        "https://www.mobafire.com/images/avatars/rell-classic.png",
        "https://www.mobafire.com/images/avatars/renekton-classic.png",
        "https://www.mobafire.com/images/avatars/rengar-classic.png",
        "https://www.mobafire.com/images/avatars/riven-classic.png",
        "https://www.mobafire.com/images/avatars/rumble-classic.png",
        "https://www.mobafire.com/images/avatars/ryze-classic.png",
        "https://www.mobafire.com/images/avatars/samira-classic.png",
        "https://www.mobafire.com/images/avatars/sejuani-classic.png",
        "https://www.mobafire.com/images/avatars/senna-classic.png",
        "https://www.mobafire.com/images/avatars/seraphine-classic.png",
        "https://www.mobafire.com/images/avatars/sett-classic.png",
        "https://www.mobafire.com/images/avatars/shaco-classic.png",
        "https://www.mobafire.com/images/avatars/shen-classic.png",
        "https://www.mobafire.com/images/avatars/shyvana-classic.png",
        "https://www.mobafire.com/images/avatars/singed-classic.png",
        "https://www.mobafire.com/images/avatars/sion-classic.png",
        "https://www.mobafire.com/images/avatars/sivir-classic.png",
        "https://www.mobafire.com/images/avatars/skarner-classic.png",
        "https://www.mobafire.com/images/avatars/sona-classic.png",
        "https://www.mobafire.com/images/avatars/soraka-classic.png",
        "https://www.mobafire.com/images/avatars/swain-classic.png",
        "https://www.mobafire.com/images/avatars/sylas-classic.png",
        "https://www.mobafire.com/images/avatars/syndra-classic.png",
        "https://www.mobafire.com/images/avatars/tahm-kench-classic.png",
        "https://www.mobafire.com/images/avatars/taliyah-classic.png",
        "https://www.mobafire.com/images/avatars/talon-classic.png",
        "https://www.mobafire.com/images/avatars/taric-classic.png",
        "https://www.mobafire.com/images/avatars/teemo-classic.png",
        "https://www.mobafire.com/images/avatars/thresh-classic.png",
        "https://www.mobafire.com/images/avatars/tristana-classic.png",
        "https://www.mobafire.com/images/avatars/trundle-classic.png",
        "https://www.mobafire.com/images/avatars/tryndamere-classic.png",
        "https://www.mobafire.com/images/avatars/twisted-fate-classic.png",
        "https://www.mobafire.com/images/avatars/twitch-classic.png",
        "https://www.mobafire.com/images/avatars/udyr-classic.png",
        "https://www.mobafire.com/images/avatars/urgot-classic.png",
        "https://www.mobafire.com/images/avatars/varus-classic.png",
        "https://www.mobafire.com/images/avatars/vayne-classic.png",
        "https://www.mobafire.com/images/avatars/veigar-classic.png",
        "https://www.mobafire.com/images/avatars/velkoz-classic.png",
        "https://www.mobafire.com/images/avatars/vi-classic.png",
        "https://www.mobafire.com/images/avatars/viktor-classic.png",
        "https://www.mobafire.com/images/avatars/vladimir-classic.png",
        "https://www.mobafire.com/images/avatars/volibear-classic.png",
        "https://www.mobafire.com/images/avatars/warwick-classic.png",
        "https://www.mobafire.com/images/avatars/wukong-classic.png",
        "https://www.mobafire.com/images/avatars/xayah-classic.png",
        "https://www.mobafire.com/images/avatars/xerath-classic.png",
        "https://www.mobafire.com/images/avatars/xin-zhao-classic.png",
        "https://www.mobafire.com/images/avatars/yasuo-classic.png",
        "https://www.mobafire.com/images/avatars/yone-classic.png",
        "https://www.mobafire.com/images/avatars/yorick-classic.png",
        "https://www.mobafire.com/images/avatars/yuumi-classic.png",
        "https://www.mobafire.com/images/avatars/zac-classic.png",
        "https://www.mobafire.com/images/avatars/zed-classic.png",
        "https://www.mobafire.com/images/avatars/ziggs-classic.png",
        "https://www.mobafire.com/images/avatars/zilean-classic.png",
        "https://www.mobafire.com/images/avatars/zoe-classic.png",
        "https://www.mobafire.com/images/avatars/zyra-classic.png",
    ]
    emailTag = "@aa.io"
    first = "Champion"
    numName = len(nameList)
    count = 0
    while count < numName:
        newUser = User(
            userName=nameList[count],
            firstName=first,
            lastName=nameList[count],
            email=nameList[count] + emailTag,
            profileImage=profilePicList[count],
            password=(f'password{count}')
        )
        count = count + 1
        db.session.add(newUser)

    db.session.commit()

# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and resets
# the auto incrementing primary key


def undo_users():
    db.session.execute('TRUNCATE users;')
    db.session.commit()
